### ISSUE TITLE
Problems running tests that depend on another repository

### ISSUE THREAD

**Issue by jakebeal** [joergbrech/moxunit-action#20]
I'd been using MOxUnit successfully for a long time with another build system, and when I needed to migrate to GitHub Actions, I figured I would use this system. I'm having difficulty, however, because my tests use some large data files that are in another repository. I can get both repositories checked out, but moxunit-action appears to run in a fixed location, and thus I'm not able to run on GitHub actions using the same relative directory convention that has worked for me in the past, since the location where it runs is unrelated to the location where checkouts occur.

**Comment by joergbrech** [comment]
Thanks for opening an issue here! Could you please provide some more information on how to reproduce this problem? Do you have the CI setup in a public repo, so that I could take a look at it? You should in principle be able to just specify the external repo location as your test directory, if the external repo is cloned in a previous step of the same job.

**Comment by jakebeal** [comment]
Thanks, @joergbrech !

Here's a failing .yml file: https://github.com/TASBE/TASBEFlowAnalytics/blob/061e6a00812c1dc4a880d41514bc61765115622c/.github/workflows/CI.yml

Here's the current working build with my workaround:
https://github.com/TASBE/TASBEFlowAnalytics/blob/7b7c334fcf424cc328c12ed6ced6115c729af8be/.github/workflows/CI.yml

**Comment by joergbrech** [comment]
If you look at the README of the checkout action: https://github.com/actions/checkout it says:

> # Relative path under $GITHUB_WORKSPACE to place the repository 
> path: '' 
> # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching # Default: true 
> clean: ''

So it seems to me, that when checking out the 2nd repo, the first one gets deleted. Also, I am not sure if the checkout action lets you checkout two different repos into the same path. Vould you check these two potential issues?

**Comment by jakebeal** [comment]
I've also taken that branch, in which case I get the repositories in persistent locations, but now MOxUnit can't find them because they aren't in /github/workspace: https://github.com/TASBE/TASBEFlowAnalytics/blob/bd9dc9861515800160aa7ecbef4576b023db04d4/.github/workflows/CI.yml

https://github.com/TASBE/TASBEFlowAnalytics/runs/2546487113?check_suite_focus=true

**Comment by joergbrech** [comment]
Intersting. So if you look at the contents of the `entrypoint.sh` file in this repo, you will see that all paths are interpreted as relative to the current working directory, as stored in the $PWD environmental variable. And despite your defaults dedinition this still seems to be /github/workspace/: https://github.com/TASBE/TASBEFlowAnalytics/runs/2546487113?check_suite_focus=true#step:5:12

So I don't know exactly why $PWD does not coincide with your specified working directory, but if you specify all all paths in the options of this repo as relative to the github workspace, you should be fine. Have you tried that as well?

**Comment by jakebeal** [comment]
It looks like there's an error when running `entrypoint.sh`:

> /entrypoint.sh: 28: [: code: unexpected operator

**Comment by jakebeal** [comment]
So far as I can tell, using relative paths positions the repositories with respect to `/home/runner/work/TASBEFlowAnalytics/TASBEFlowAnalytics`, while the docker command that you reference appears to be coming from `moxunit-action` and be placing things relative to `/home/runner/work/_temp/`.
Notably, the relative path to the second repository would be: `/github/workspace/../TASBEFlowAnalytics-Tutorial`, which doesn't seem to map within the docker environment.

I could try to check out the repositories into `/home/runner/work/_temp/` instead, but that seems like a questionable kludge.

Am I misunderstanding something?

**Comment by joergbrech** [comment]
Ah ok, so  I think I now know where I misunderstood things. 

 - Docker actually mounts the working directory `home/runner/work/TASBEFlowAnalytics/TASBEFlowAnalytics` under `/github/workspace` in the docker image, so that works. See https://github.com/TASBE/TASBEFlowAnalytics/runs/2546487113?check_suite_focus=true#step:5:6, `-v "/home/runner/work/TASBEFlowAnalytics/TASBEFlowAnalytics":"/github/workspace"`.
 - Your CI job fails, because moxunit-action cannot find the directory `/github/workspace/tests`: https://github.com/TASBE/TASBEFlowAnalytics/runs/2546487113?check_suite_focus=true#step:5:28
 - And it is actually not there, because you checkout your repo into `/home/runner/work/TASBEFlowAnalytics/TASBEFlowAnalytics/TASBEFlowAnalytics`, see https://github.com/TASBE/TASBEFlowAnalytics/runs/2546487113?check_suite_focus=true#step:4:18. Note the extra `TASBEFlowAnalytics`, which comes from https://github.com/TASBE/TASBEFlowAnalytics/blob/bd9dc9861515800160aa7ecbef4576b023db04d4/.github/workflows/CI.yml#L21

So I don't think this is an issue with moxunit-action. Here is what I would do:
 - Don't specify a working directory, use the default
 - Don't specify a `path` when you checkout your repo. This will checkout your repo directly into the workspace. 
 - Specify a relative `path` when you checkout `TASBEFlowAnalytics-Tutorial`.

Could you please try this as well? Thanks for your patience

**Comment by joergbrech** [comment]
@jakebeal, I added the option to specify a working directory and made a suggestion for a workflow file here: https://github.com/TASBE/TASBEFlowAnalytics/pull/524. The relative path issue seems to be resolved, but I do get some failed tests in my fork of TASBEFlowAnalytics. I will have very limited access to the internet for the next three weeks starting tomorrow, so I hope that you can work with the proposed changes.

**Comment by joergbrech** [comment]
> Is the right patch for that adding the tests to the src: variable or having moxunit-action add the tests: directories to the path?

Valid question, I think I personally would prefer the first option, because it's more explicit and it wouldn't require a modification of moxunit-action 🙂

**Comment by jakebeal** [comment]
Can you please add that to your pull request so that we can see if that allows the tests to pass?

**Comment by joergbrech** [comment]
Done

**Comment by jakebeal** [comment]
That depends on the test suite being executed in a specific order, and would be fragile to addition of new test files.
Would it be possible to have moxunit-action support a pre-test initialization hook, where one could point to an arbitrary pre-test file to run? (presumably some might also want a post-test hook)

This would then be more symmetric with the pattern suggested in MOxUnit

**Comment by joergbrech** [comment]
Sure this is good option, and probably useful. I just won't be able to do this today and I will be away from my computer for a few weeks starting tomorrow. Feel free to open an issue here for this. Contributions are of course also very welcome here, maybe I will even find the time for a quick review while I am away. Otherwise, you would have to live with a workaround for now.

**Comment by jakebeal** [comment]
Filed the issue. Since I have a workaround running, it's fine if this waits for a few weeks.
If I happen to find time myself, I will try to address it, but given the number of other commitments I have, that is unlikely.

**Comment by jakebeal** [comment]
The test suite initialization approach worked well. 
If you are interested to see the final merge, it is in https://github.com/TASBE/TASBEFlowAnalytics/pull/529
