### ISSUE TITLE
Basic Matlab Functions Not Defined

### ISSUE THREAD

**Issue by zyigo** [joergbrech/moxunit-action#8]
Hi Jeorg,

I'm currently developing a MATLAB toolbox for importing mocap ASF and AMC files and would like to set up a really basic CI testing set using this awesome repo.

## Issue
When running some really simple tests with this action, I'm getting the following error in one of my recent failed [runs](https://github.com/zyigo/AMC-ASF-Tools/runs/1075012698?check_suite_focus=true) :

> 'split' undefined near line 215 column 51
> LoadSkeleton>checkFileCorrect:215 (/tmp/oct-S1IzVd/LoadSkeleton.m)

FYI, in the [LoadSkeleton.m](https://github.com/zyigo/AMC-ASF-Tools/blob/87b9c82de1690dd119d178bf86b75f697d2f117a/AMC-ASF-Tools/tbx/AMC-ASF-Tools/LoadSkeleton.m) file, I am simply converting a basic char array into a string under the following:
``` matlab
function checkFileCorrect(path)
   path = string(path);
% etc.
```
I should note too, this script runs perfectly in MATLAB and I have had this for other MATLAB functions like _convertCharToStrings(...)_

## Question
I'm new to CI and deployment testing - Is this an issue with my [action implementation](https://github.com/zyigo/AMC-ASF-Tools/blob/87b9c82de1690dd119d178bf86b75f697d2f117a/.github/workflows/RunTests.yml) , or is there something else going on?

**Comment by joergbrech** [comment]
@zyigo, thanks for opening the issue here! As far as I can tell your action implementation is correct. The CI uses Octave 4.2.2 under the hood and according to [this doc page](https://octave.org/doc/v4.2.2/Obsolete-Functions.html) the utility function `split` has become obsolete in version 3.6.0. The page suggests to replace `split` with `char (strsplit (s, t))`. Or you could just write your own wrapper

```matlab
function res = split(s, t)
   res = char (strsplit (s, t))
```

Could you please let me know if this resolves your problem?

**Comment by zyigo** [comment]
Yep that works! Cheers mate! I'll keep that page in mind!
